controller_list:
  - name: fake_rrr_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
  - name: fake_rrr_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - grip_right
initial:  # Define initial robot poses per group
  - group: rrr_arm
    pose: home