arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
  gains:
    joint_1:
      p: 150
      d: 10
      i: 1
      i_clamp: 1
    joint_2:
      p: 100
      d: 10
      i: 1
      i_clamp: 1
    joint_3:
      p: 100
      d: 10
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - grip_right
    - grip_left
  gains:
    grip_right:
      p: 100
      d: 10
      i: 1
      i_clamp: 1
    grip_left:
      p: 100
      d: 10
      i: 1
      i_clamp: 1
controller_list:
  - name: rrr_arm/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
  - name: rrr_arm/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - grip_right
      - grip_left